### ISSUE TITLE
Support Mastech MS6514 as an option with the SR700 Server

### ISSUE THREAD

**Issue by donicrosby** [lucapinello/SR700_Artisan_Server#8]
I recently received a MS6514 to use with Artisan would it be possible to integrate this with the server as done with the phidget?

**Comment by sychan** [comment]
@lucapinello First off, thank you for taking the time to add phidget and max31865 support, and integrate the Roastero controller module into this Artisan Server. I had a similar question @donicrosby however I went crawling through the source to see the work involved, and it looks like it would be very similar to the PR from @alvaroGomides ( https://github.com/lucapinello/freshroastsr700_phidget/pull/2 ) however the code would just have to be modified for the protocol from the cp210x serial driver.

But I'm wondering if there is an even easier way? For the PID control, you suggested using the Artisan PID control code, and the main Artisan codebase already has support for reading temps from the Mastech MS6514. Can you suggest how to modify the artisan-settings_sr700.aset file so that it uses your main server code for control of the fan and heater, but uses the Artisan MS6514 support for reading temperature?

**Comment by sychan** [comment]
Actually, I didn't realize that Luca was in the Facebook FreshRoast Coffee Roasters group and there was a thread there where Wyatt Maurer reported success using this server and then selecting the MS6514 from within Artisan for the temperature settings. This link should lead you to the relevant comments in FB, but you will need to be a member of both FB and the Freshroast Coffee Roasters group:
https://www.facebook.com/groups/1471311819774625/posts/2408788879360243/?comment_id=2408800742692390&reply_comment_id=2411463399092791

**Comment by sychan** [comment]
For people who can't or won't participate in the FB group, here's the relevant comments. I think this issue can be closed, since it is a solved problem.

> [Wyatt Macfarlane Maurer] got it working with the artisan pid and the mastech!
> [Darren Addy] Sweet! So you created a profile in the Profile Builder and then drove that roast to profile using the Artisan PID? Can you detail the steps you went through to get there, please?
> [Luca Pinello] great! Now share your best profiles 🙂
> [Wyatt Macfarlane Maurer] Yep. Used the designer under tools dropdown in artisan saved profile and loaded it in the background. followed the instructions on Luca's github page for setting up/starting the server in "artisan PID mode" and hooked up my Mastech to give me the temp readings that the artisan software PID would go off of.
> [Darren Addy] Thank you Wyatt. Did you also load the new .aset file that Luca provided into Artisan? Also, have you messed with the PID numbers at all? What values are you using? Thanks!
> [Wyatt Macfarlane Maurer] I used this .aset file....
> https://raw.githubusercontent.com/lucapinello/SR700_Artisan_Server/master/SR700_Artisan_Server/settings/artisan-settings_sr700.aset
>

**Comment by lucapinello** [comment]
Thanks for reporting this here! Closing this.
